/*!
 * Piwik - Web Analytics
 *
 * JavaScript tracking client
 *
 * @link http://piwik.org
 * @source https://github.com/piwik/piwik/blob/master/js/piwik.js
 * @license http://piwik.org/free-software/bsd/ Simplified BSD (also in js/LICENSE.txt)
 */
"object"!==typeof JSON2&&(JSON2={});
(function(){function b(b){return 10>b?"0"+b:b}function C(b){d.lastIndex=0;return d.test(b)?'"'+b.replace(d,function(b){var h=K[b];return"string"===typeof h?h:"\\u"+("0000"+b.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+b+'"'}function p(d,P){var h,u,t,L,Y=l,s,e=P[d];e&&"object"===typeof e&&(h=e,t=Object.prototype.toString.apply(h),e="[object Date]"===t?isFinite(h.valueOf())?h.getUTCFullYear()+"-"+b(h.getUTCMonth()+1)+"-"+b(h.getUTCDate())+"T"+b(h.getUTCHours())+":"+b(h.getUTCMinutes())+":"+b(h.getUTCSeconds())+
"Z":null:"[object String]"===t||"[object Number]"===t||"[object Boolean]"===t?h.valueOf():"[object Array]"!==t&&"function"===typeof h.toJSON?h.toJSON(d):h);"function"===typeof A&&(e=A.call(P,d,e));switch(typeof e){case "string":return C(e);case "number":return isFinite(e)?String(e):"null";case "boolean":case "null":return String(e);case "object":if(!e)return"null";l+=v;s=[];if("[object Array]"===Object.prototype.toString.apply(e)){L=e.length;for(h=0;h<L;h+=1)s[h]=p(h,e)||"null";t=0===s.length?"[]":
l?"[\n"+l+s.join(",\n"+l)+"\n"+Y+"]":"["+s.join(",")+"]";l=Y;return t}if(A&&"object"===typeof A)for(L=A.length,h=0;h<L;h+=1)"string"===typeof A[h]&&(u=A[h],(t=p(u,e))&&s.push(C(u)+(l?": ":":")+t));else for(u in e)Object.prototype.hasOwnProperty.call(e,u)&&(t=p(u,e))&&s.push(C(u)+(l?": ":":")+t);t=0===s.length?"{}":l?"{\n"+l+s.join(",\n"+l)+"\n"+Y+"}":"{"+s.join(",")+"}";l=Y;return t}}var G=RegExp("[\x00\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]",
"g"),d=RegExp('[\\\\\\"\x00-\u001f\u007f-\u009f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]',"g"),l,v,K={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},A;"function"!==typeof JSON2.stringify&&(JSON2.stringify=function(b,d,h){var u;v=l="";if("number"===typeof h)for(u=0;u<h;u+=1)v+=" ";else"string"===typeof h&&(v=h);if((A=d)&&"function"!==typeof d&&("object"!==typeof d||"number"!==typeof d.length))throw Error("JSON2.stringify");
return p("",{"":b})});"function"!==typeof JSON2.parse&&(JSON2.parse=function(b,d){function h(b,l){var p,s,e=b[l];if(e&&"object"===typeof e)for(p in e)Object.prototype.hasOwnProperty.call(e,p)&&(s=h(e,p),void 0!==s?e[p]=s:delete e[p]);return d.call(b,l,e)}var l;b=String(b);G.lastIndex=0;G.test(b)&&(b=b.replace(G,function(b){return"\\u"+("0000"+b.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(b.replace(RegExp('\\\\(?:["\\\\/bfnrt]|u[0-9a-fA-F]{4})',"g"),"@").replace(RegExp('"[^"\\\\\n\r]*"|true|false|null|-?\\d+(?:\\.\\d*)?(?:[eE][+\\-]?\\d+)?',
"g"),"]").replace(RegExp("(?:^|:|,)(?:\\s*\\[)+","g"),"")))return l=eval("("+b+")"),"function"===typeof d?h({"":l},""):l;throw new SyntaxError("JSON2.parse");})})();"object"!==typeof _paq&&(_paq=[]);
"object"!==typeof Piwik&&(Piwik=function(){function b(c){return"undefined"!==typeof c}function C(c){return"object"===typeof c}function p(c){return"string"===typeof c||c instanceof String}function G(){var c,b,n;for(c=0;c<arguments.length;c+=1)n=arguments[c],b=n.shift(),p(b)?J[b].apply(J,n):b.apply(J,n)}function d(c,b,n,f){if(c.addEventListener)return c.addEventListener(b,n,f),!0;if(c.attachEvent)return c.attachEvent("on"+b,n);c["on"+b]=n}function l(c,b){var n="",f,d;for(f in Z)Object.prototype.hasOwnProperty.call(Z,
f)&&(d=Z[f][c],"function"===typeof d&&(n+=d(b)));return n}function v(){var c;if(!ca)for(ca=!0,l("load"),c=0;c<ra.length;c++)ra[c]();return!0}function K(c,b){var n=k.createElement("script");n.type="text/javascript";n.src=c;n.readyState?n.onreadystatechange=function(){var c=this.readyState;if("loaded"===c||"complete"===c)n.onreadystatechange=null,b()}:n.onload=b;k.getElementsByTagName("head")[0].appendChild(n)}function A(){var c="";try{c=m.top.document.referrer}catch(b){if(m.parent)try{c=m.parent.document.referrer}catch(n){c=
""}}""===c&&(c=k.referrer);return c}function Fa(c){return(c=/^([a-z]+):/.exec(c))?c[1]:null}function P(c){var b=/^(?:(?:https?|ftp):)\/*(?:[^@]+@)?([^:/#]+)/.exec(c);return b?b[1]:c}function h(c,b){var n=(new RegExp("[\\?&#]"+b+"=([^&#]*)")).exec(c);return n?Ga(n[1]):""}function u(c){var b=function(c,b){return c<<b|c>>>32-b},n=function(c){var b="",d,f;for(d=7;0<=d;d--)f=c>>>4*d&15,b+=f.toString(16);return b},f,d,h=[],l=1732584193,m=4023233417,k=2562383102,e=271733878,p=3285377520,q,w,r,t,s,v=[];c=
Ia(y(c));q=c.length;for(f=0;f<q-3;f+=4)d=c.charCodeAt(f)<<24|c.charCodeAt(f+1)<<16|c.charCodeAt(f+2)<<8|c.charCodeAt(f+3),v.push(d);switch(q&3){case 0:f=2147483648;break;case 1:f=c.charCodeAt(q-1)<<24|8388608;break;case 2:f=c.charCodeAt(q-2)<<24|c.charCodeAt(q-1)<<16|32768;break;case 3:f=c.charCodeAt(q-3)<<24|c.charCodeAt(q-2)<<16|c.charCodeAt(q-1)<<8|128}for(v.push(f);14!==(v.length&15);)v.push(0);v.push(q>>>29);v.push(q<<3&4294967295);for(c=0;c<v.length;c+=16){for(f=0;16>f;f++)h[f]=v[c+f];for(f=
16;79>=f;f++)h[f]=b(h[f-3]^h[f-8]^h[f-14]^h[f-16],1);d=l;q=m;w=k;r=e;t=p;for(f=0;19>=f;f++)s=b(d,5)+(q&w|~q&r)+t+h[f]+1518500249&4294967295,t=r,r=w,w=b(q,30),q=d,d=s;for(f=20;39>=f;f++)s=b(d,5)+(q^w^r)+t+h[f]+1859775393&4294967295,t=r,r=w,w=b(q,30),q=d,d=s;for(f=40;59>=f;f++)s=b(d,5)+(q&w|q&r|w&r)+t+h[f]+2400959708&4294967295,t=r,r=w,w=b(q,30),q=d,d=s;for(f=60;79>=f;f++)s=b(d,5)+(q^w^r)+t+h[f]+3395469782&4294967295,t=r,r=w,w=b(q,30),q=d,d=s;l=l+d&4294967295;m=m+q&4294967295;k=k+w&4294967295;e=e+r&
4294967295;p=p+t&4294967295}s=n(l)+n(m)+n(k)+n(e)+n(p);return s.toLowerCase()}function t(c,b,d){if("translate.googleusercontent.com"===c)""===d&&(d=b),b=h(b,"u"),c=P(b);else if("cc.bingj.com"===c||"webcache.googleusercontent.com"===c||"74.6."===c.slice(0,5))b=k.links[0].href,c=P(b);return[c,b,d]}function L(c){var b=c.length;"."===c.charAt(--b)&&(c=c.slice(0,b));"*."===c.slice(0,2)&&(c=c.slice(1));return c}function Y(c){c=c&&c.text?c.text:c;if(!p(c)){var d=k.getElementsByTagName("title");d&&b(d[0])&&
(c=d[0].text)}return c}function s(c,b){if(b)return b;"piwik.php"===c.slice(-9)&&(c=c.slice(0,c.length-9));return c}function e(b){var d=/index\.php\?module=Overlay&action=startOverlaySession&idSite=([0-9]+)&period=([^&]+)&date=([^&]+)$/.exec(k.referrer);if(d){if(d[1]!==String(b))return!1;m.name="Piwik_Overlay###"+d[2]+"###"+d[3]}b=m.name.split("###");return 3===b.length&&"Piwik_Overlay"===b[0]}function ib(b,d,h){var f=m.name.split("###"),l=f[1],k=f[2],e=s(b,d);K(e+"plugins/Overlay/client/client.js?v=1",
function(){Piwik_Overlay_Client.initialize(e,h,l,k)})}function da(c,s){function n(a,g,b,c,d,f){if(!R){var h;b&&(h=new Date,h.setTime(h.getTime()+b));k.cookie=a+"="+y(g)+(b?";expires="+h.toGMTString():"")+";path="+(c||"/")+(d?";domain="+d:"")+(f?";secure":"")}}function f(a){return R?0:(a=(new RegExp("(^|;)[ ]*"+a+"=([^;]*)")).exec(k.cookie))?Ga(a[2]):0}function v(a){var g;return Ja?(g=/#.*/,a.replace(g,"")):a}function G(a){var g,b,c;for(g=0;g<ia.length;g++){b=L(ia[g].toLowerCase());if(a===b)return!0;
if("."===b.slice(0,1)){if(a===b.slice(1))return!0;c=a.length-b.length;if(0<c&&a.slice(c)===b)return!0}}return!1}function K(a){var g=new Image(1,1);g.onload=function(){z=0};g.src=ea+(0>ea.indexOf("?")?"?":"&")+a}function J(a){try{var g=m.XMLHttpRequest?new m.XMLHttpRequest:m.ActiveXObject?new ActiveXObject("Microsoft.XMLHTTP"):null;g.open("POST",ea,!0);g.onreadystatechange=function(){4===this.readyState&&200!==this.status&&K(a)};g.setRequestHeader("Content-Type","application/x-www-form-urlencoded; charset=UTF-8");
g.send(a)}catch(b){K(a)}}function E(a,g){var b=new Date;sa||("POST"===Ka?J(a):K(a),ta=b.getTime()+g)}function I(a){return La+a+"."+fa+"."+Ma}function X(){if(R)return"0";if(!b(B.cookieEnabled)){var a=I("testcookie");n(a,"1");return"1"===f(a)?"1":"0"}return B.cookieEnabled?"1":"0"}function q(){Ma=Na((N||ua)+(O||"/")).slice(0,4)}function w(){var a=I("cvar"),a=f(a);return a.length&&(a=JSON2.parse(a),C(a))?a:{}}function r(){va=(new Date).getTime()}function Z(a,g,b,c,d,f){n(I("id"),a+"."+g+"."+b+"."+c+
"."+d+"."+f,Oa,O,N)}function W(){var a=new Date,g=Math.round(a.getTime()/1E3),b=f(I("id"));b?(a=b.split("."),a.unshift("0")):(wa||(wa=Na((B.userAgent||"")+(B.platform||"")+JSON2.stringify(Q)+a.getTime()+Math.random()).slice(0,16)),a=["1",wa,g,0,g,"",""]);return a}function $(){var a=f(I("ref"));if(a.length)try{if(a=JSON2.parse(a),C(a))return a}catch(g){}return["","",0,""]}function ba(){var a=R;R=!1;n(I("id"),"",-86400,O,N);n(I("ses"),"",-86400,O,N);n(I("cvar"),"",-86400,O,N);n(I("ref"),"",-86400,O,
N);R=a}function da(a){if(a&&C(a)){var g=[],b;for(b in a)Object.prototype.hasOwnProperty.call(a,b)&&g.push(b);b={};g.sort();var c=g.length,d;for(d=0;d<c;d++)b[g[d]]=a[g[d]];return b}}function M(a,g,c,d){function m(a,g){var b=JSON2.stringify(a);return 2<b.length?"&"+g+"="+y(b):""}var e,S=new Date,q=Math.round(S.getTime()/1E3),p,s,r,t,w,x,u,B,A,z,C=F,K=I("ses"),L=I("ref"),M=I("cvar");u=W();z=f(K);var D=$(),J=ja||Pa,T,E;R&&ba();if(sa)return"";p=u[0];s=u[1];t=u[2];r=u[3];w=u[4];x=u[5];b(u[6])||(u[6]="");
u=u[6];b(d)||(d="");var H=k.characterSet||k.charset;H&&"utf-8"!==H.toLowerCase()||(H=null);T=D[0];E=D[1];B=D[2];A=D[3];if(!z){z=ka/1E3;if(!x||q-x>z)r++,x=w;if(!xa||!T.length){for(e in la)if(Object.prototype.hasOwnProperty.call(la,e)&&(T=h(J,la[e]),T.length))break;for(e in ma)if(Object.prototype.hasOwnProperty.call(ma,e)&&(E=h(J,ma[e]),E.length))break}w=P(ga);z=A.length?P(A):"";!w.length||G(w)||xa&&z.length&&!G(z)||(A=ga);if(A.length||T.length)B=q,D=[T,E,B,v(A.slice(0,1024))],n(L,JSON2.stringify(D),
Qa,O,N)}a+="&idsite="+fa+"&rec=1&r="+String(Math.random()).slice(2,8)+"&h="+S.getHours()+"&m="+S.getMinutes()+"&s="+S.getSeconds()+"&url="+y(v(J))+(ga.length?"&urlref="+y(v(ga)):"")+"&_id="+s+"&_idts="+t+"&_idvc="+r+"&_idn="+p+(T.length?"&_rcn="+y(T):"")+(E.length?"&_rck="+y(E):"")+"&_refts="+B+"&_viewts="+x+(String(u).length?"&_ects="+u:"")+(String(A).length?"&_ref="+y(v(A.slice(0,1024))):"")+(H?"&cs="+y(H):"");for(e in Q)Object.prototype.hasOwnProperty.call(Q,e)&&(a+="&"+e+"="+Q[e]);g?a+="&data="+
y(JSON2.stringify(g)):U&&(a+="&data="+y(JSON2.stringify(U)));g=da(V);S=da(ya);a+=m(g,"cvar");a+=m(S,"e_cvar");if(F){a+=m(F,"_cvar");for(e in C)Object.prototype.hasOwnProperty.call(C,e)&&(""!==F[e][0]&&""!==F[e][1]||delete F[e]);n(M,JSON2.stringify(F),ka,O,N)}Ra&&(za?a+="&gt_ms="+za:aa&&aa.timing&&aa.timing.requestStart&&aa.timing.responseEnd&&(a+="&gt_ms="+(aa.timing.responseEnd-aa.timing.requestStart)));Z(s,t,r,q,x,b(d)&&String(d).length?d:u);n(K,"*",ka,O,N);a+=l(c);Aa.length&&(a+="&"+Aa);return a}
function Ha(a,g,c,d,f,h){var e="idgoal=0",l,m=new Date,n=[],k;String(a).length&&(e+="&ec_id="+y(a),l=Math.round(m.getTime()/1E3));e+="&revenue="+g;String(c).length&&(e+="&ec_st="+c);String(d).length&&(e+="&ec_tx="+d);String(f).length&&(e+="&ec_sh="+f);String(h).length&&(e+="&ec_dt="+h);if(x){for(k in x)Object.prototype.hasOwnProperty.call(x,k)&&(b(x[k][1])||(x[k][1]=""),b(x[k][2])||(x[k][2]=""),b(x[k][3])&&0!==String(x[k][3]).length||(x[k][3]=0),b(x[k][4])&&0!==String(x[k][4]).length||(x[k][4]=1),
n.push(x[k]));e+="&ec_items="+y(JSON2.stringify(n))}e=M(e,U,"ecommerce",l);E(e,D);x={}}function kb(a,g){var b=new Date,c=M("action_name="+y(Y(a||Sa)),g,"log");E(c,D);Ba&&ha&&!Ta&&(Ta=!0,d(k,"click",r),d(k,"mouseup",r),d(k,"mousedown",r),d(k,"mousemove",r),d(k,"mousewheel",r),d(m,"DOMMouseScroll",r),d(m,"scroll",r),d(k,"keypress",r),d(k,"keydown",r),d(k,"keyup",r),d(m,"resize",r),d(m,"focus",r),d(m,"blur",r),va=b.getTime(),setTimeout(function jb(){var a;b=new Date;va+ha>b.getTime()&&(Ba<b.getTime()&&
(a=M("ping=1",g,"ping"),E(a,D)),setTimeout(jb,ha))},ha))}function Ua(a,g,c,d,e){if(0===String(a).length||0===String(g).length)return!1;a=M("e_c="+y(a)+"&e_a="+y(g)+(b(c)?"&e_n="+y(c):"")+(b(d)?"&e_v="+y(d):""),e,"event");E(a,D)}function Va(a,g,b){a=M(g+"="+y(v(a)),b,"link");E(a,D)}function Wa(a,g){return""!==a?a+g.charAt(0).toUpperCase()+g.slice(1):g}function H(a){var g,b,c=["","webkit","ms","moz"],e;if(!Xa)for(b=0;b<c.length;b++)if(e=c[b],Object.prototype.hasOwnProperty.call(k,Wa(e,"hidden"))){"prerender"===
k[Wa(e,"visibilityState")]&&(g=!0);break}g?d(k,e+"visibilitychange",function S(){k.removeEventListener(e+"visibilitychange",S,!1);a()}):a()}function Ca(a,b){var c,d="(^| )(piwik[_-]"+b;if(a)for(c=0;c<a.length;c++)d+="|"+a[c];return new RegExp(d+")( |$)")}function Ya(a){var g,c;for(g=a.parentNode;null!==g&&b(g);){c=a.tagName.toUpperCase();if("A"===c||"AREA"===c)break;a=g;g=a.parentNode}if(b(a.href)){g=a.hostname||P(a.href);var d=g.toLowerCase();g=a.href.replace(g,d);if(!/^(javascript|vbscript|jscript|mocha|livescript|ecmascript|mailto):/i.test(g)){a=
a.className;c=g;var d=G(d),e=Ca(Za,"download"),f=Ca($a,"link"),h=new RegExp("\\.("+na+")([?&#]|$)","i");if(a=f.test(a)?"link":e.test(a)||h.test(c)?"download":d?0:"link")g=Ia(g),Va(g,a)}}}function Da(a){var b,c;a=a||m.event;b=a.which||a.button;c=a.target||a.srcElement;"click"===a.type?c&&Ya(c):"mousedown"===a.type?1!==b&&2!==b||!c?oa=pa=null:(oa=b,pa=c):"mouseup"===a.type&&(b===oa&&c===pa&&Ya(c),oa=pa=null)}function ab(a,b){b?(d(a,"mouseup",Da,!1),d(a,"mousedown",Da,!1)):d(a,"click",Da,!1)}function bb(a){if(!cb){cb=
!0;var b,c=Ca(db,"ignore"),d=k.links;if(d)for(b=0;b<d.length;b++)c.test(d[b].className)||ab(d[b],a)}}var qa={},Ea=t(k.domain,m.location.href,A()),ua=L(Ea[0]),Pa=Ea[1],ga=Ea[2],eb=!1,Ka="GET",ea=c||"",fb="",Aa="",fa=s||"",ja,Sa=k.title,na="7z|aac|apk|ar[cj]|as[fx]|avi|azw3|bin|csv|deb|dmg|docx?|epub|exe|flv|gif|gz|gzip|hqx|jar|jpe?g|js|mobi|mp(2|3|4|e?g)|mov(ie)?|ms[ip]|od[bfgpst]|og[gv]|pdf|phps|png|pptx?|qtm?|ra[mr]?|rpm|sea|sit|tar|t?bz2?|tgz|torrent|txt|wav|wm[av]|wpd||xlsx?|xml|z|zip",ia=[ua],
db=[],Za=[],$a=[],D=500,Ba,ha,Ja,U,la=["pk_campaign","piwik_campaign","utm_campaign","utm_source","utm_medium"],ma=["pk_kwd","piwik_kwd","utm_term"],La="_pk_",N,O,R=!1,sa,Xa,xa,Oa=63072E6,ka=18E5,Qa=15768E6,Ra=!0,za=0,F=!1,V={},ya={},x={},Q={},cb=!1,Ta=!1,va,oa,pa,Na=u,Ma,wa;(function(){var a,c,d={pdf:"application/pdf",qt:"video/quicktime",realp:"audio/x-pn-realaudio-plugin",wma:"application/x-mplayer2",dir:"application/x-director",fla:"application/x-shockwave-flash",java:"application/x-java-vm",
gears:"application/x-googlegears",ag:"application/x-silverlight"},e=/Mac OS X.*Safari\//.test(B.userAgent)?m.devicePixelRatio||1:1;if(!/MSIE/.test(B.userAgent)){if(B.mimeTypes&&B.mimeTypes.length)for(a in d)Object.prototype.hasOwnProperty.call(d,a)&&(c=B.mimeTypes[d[a]],Q[a]=c&&c.enabledPlugin?"1":"0");"unknown"!==typeof navigator.javaEnabled&&b(B.javaEnabled)&&B.javaEnabled()&&(Q.java="1");"function"===typeof m.GearsFactory&&(Q.gears="1");Q.cookie=X()}Q.res=gb.width*e+"x"+gb.height*e})();q();l("run",
function(a,c){var d=null;if(p(a)&&!b(qa[a])&&c){if(C(c))d=c;else if(p(c))try{eval("hookObj ="+c)}catch(e){}qa[a]=d}return d});return{hook:qa,getHook:function(a){return qa[a]},getVisitorId:function(){return W()[1]},getVisitorInfo:function(){return W()},getAttributionInfo:function(){return $()},getAttributionCampaignName:function(){return $()[0]},getAttributionCampaignKeyword:function(){return $()[1]},getAttributionReferrerTimestamp:function(){return $()[2]},getAttributionReferrerUrl:function(){return $()[3]},
setTrackerUrl:function(a){ea=a},setSiteId:function(a){fa=a},setCustomData:function(a,b){C(a)?U=a:(U||(U=[]),U[a]=b)},getCustomData:function(){return U},appendToTrackingUrl:function(a){Aa=a},getRequest:function(a){return M(a)},setCustomVariable:function(a,c,d,e){b(e)||(e="visit");b(c)&&(b(d)||(d=""),0<a&&(c=p(c)?c:String(c),d=p(d)?d:String(d),c=[c.slice(0,200),d.slice(0,200)],"visit"===e||2===e?(!1===F&&(F=w()),F[a]=c):"page"===e||3===e?V[a]=c:"event"===e&&(ya[a]=c)))},getCustomVariable:function(a,
c){var d;b(c)||(c="visit");if("page"===c||3===c)d=V[a];else if("event"===c)d=ya[a];else if("visit"===c||2===c)!1===F&&(F=w()),d=F[a];return!b(d)||d&&""===d[0]?!1:d},deleteCustomVariable:function(a,b){this.getCustomVariable(a,b)&&this.setCustomVariable(a,"","",b)},setLinkTrackingTimer:function(a){D=a},setDownloadExtensions:function(a){na=a},addDownloadExtensions:function(a){na+="|"+a},setDomains:function(a){ia=p(a)?[a]:a;ia.push(ua)},setIgnoreClasses:function(a){db=p(a)?[a]:a},setRequestMethod:function(a){Ka=
a||"GET"},setReferrerUrl:function(a){ga=a},setCustomUrl:function(a){var b=Pa,c;Fa(a)?ja=a:"/"===a.slice(0,1)?ja=Fa(b)+"://"+P(b)+a:(b=v(b),c=b.indexOf("?"),0<=c&&(b=b.slice(0,c)),c=b.lastIndexOf("/"),c!==b.length-1&&(b=b.slice(0,c+1)),ja=b+a)},setDocumentTitle:function(a){Sa=a},setAPIUrl:function(a){fb=a},setDownloadClasses:function(a){Za=p(a)?[a]:a},setLinkClasses:function(a){$a=p(a)?[a]:a},setCampaignNameKey:function(a){la=p(a)?[a]:a},setCampaignKeywordKey:function(a){ma=p(a)?[a]:a},discardHashTag:function(a){Ja=
a},setCookieNamePrefix:function(a){La=a;F=w()},setCookieDomain:function(a){N=L(a);q()},setCookiePath:function(a){O=a;q()},setVisitorCookieTimeout:function(a){Oa=1E3*a},setSessionCookieTimeout:function(a){ka=1E3*a},setReferralCookieTimeout:function(a){Qa=1E3*a},setConversionAttributionFirstReferrer:function(a){xa=a},disableCookies:function(){R=!0},deleteCookies:function(){ba()},setDoNotTrack:function(a){var b=B.doNotTrack||B.msDoNotTrack;(sa=a&&("yes"===b||"1"===b))&&this.disableCookies()},addListener:function(a,
b){ab(a,b)},enableLinkTracking:function(a){ca?bb(a):ra.push(function(){bb(a)})},enableJSErrorTracking:function(){if(!eb){eb=!0;var a=m.onerror;m.onerror=function(b,c,d,e,f){H(function(){var a=c+":"+d;e&&(a+=":"+e);Ua("JavaScript Errors",a,b)});return a?a(b,c,d,e,f):!1}}},disablePerformanceTracking:function(){Ra=!1},setGenerationTimeMs:function(a){za=parseInt(a,10)},setHeartBeatTimer:function(a,b){Ba=(new Date).getTime()+1E3*a;ha=1E3*b},killFrame:function(){m.location!==m.top.location&&(m.top.location=
m.location)},redirectFile:function(a){"file:"===m.location.protocol&&(m.location=a)},setCountPreRendered:function(a){Xa=a},trackGoal:function(a,b,c){H(function(){var d=M("idgoal="+a+(b?"&revenue="+b:""),c,"goal");E(d,D)})},trackLink:function(a,b,c){H(function(){Va(a,b,c)})},trackPageView:function(a,b){e(fa)?H(function(){ib(ea,fb,fa)}):H(function(){kb(a,b)})},trackEvent:function(a,b,c,d){H(function(){Ua(a,b,c,d)})},trackSiteSearch:function(a,c,d){H(function(){var e=M("search="+y(a)+(c?"&search_cat="+
y(c):"")+(b(d)?"&search_count="+d:""),void 0,"sitesearch");E(e,D)})},setEcommerceView:function(a,c,d,e){b(d)&&d.length?d instanceof Array&&(d=JSON2.stringify(d)):d="";V[5]=["_pkc",d];b(e)&&String(e).length&&(V[2]=["_pkp",e]);if(b(a)&&a.length||b(c)&&c.length)b(a)&&a.length&&(V[3]=["_pks",a]),b(c)&&c.length||(c=""),V[4]=["_pkn",c]},addEcommerceItem:function(a,b,c,d,e){a.length&&(x[a]=[a,b,c,d,e])},trackEcommerceOrder:function(a,c,d,e,f,h){String(a).length&&b(c)&&Ha(a,c,d,e,f,h)},trackEcommerceCartUpdate:function(a){b(a)&&
Ha("",a,"","","","")}}}var ta,Z={},k=document,B=navigator,gb=screen,m=window,aa=m.performance||m.mozPerformance||m.msPerformance||m.webkitPerformance,ca=!1,ra=[],y=m.encodeURIComponent,Ga=m.decodeURIComponent,Ia=unescape,J,z,W;d(m,"beforeunload",function(){var b;l("unload");if(ta){do b=new Date;while(b.getTimeAlias()<ta)}},!1);(function(){var b;k.addEventListener?d(k,"DOMContentLoaded",function n(){k.removeEventListener("DOMContentLoaded",n,!1);v()}):k.attachEvent&&(k.attachEvent("onreadystatechange",
function f(){"complete"===k.readyState&&(k.detachEvent("onreadystatechange",f),v())}),k.documentElement.doScroll&&m===m.top&&function hb(){if(!ca){try{k.documentElement.doScroll("left")}catch(b){setTimeout(hb,0);return}v()}}());/WebKit/.test(B.userAgent)&&(b=setInterval(function(){if(ca||/loaded|complete/.test(k.readyState))clearInterval(b),v()},10));d(m,"load",v,!1)})();Date.prototype.getTimeAlias=Date.prototype.getTime;J=new da;var ba={setTrackerUrl:1,setAPIUrl:1,setSiteId:1},X;for(z=0;z<_paq.length;z++)X=
_paq[z][0],ba[X]&&(G(_paq[z]),delete _paq[z],1<ba[X]&&void 0!==console&&console&&console.error&&console.error("The method "+X+' is registered more than once in "_paq" variable. Only the last call has an effect. Please have a look at the multiple Piwik trackers documentation: http://developer.piwik.org/api-reference/tracking-javascript#multiple-piwik-trackers'),ba[X]++);for(z=0;z<_paq.length;z++)_paq[z]&&G(_paq[z]);_paq=new function(){return{push:G}};W={addPlugin:function(b,d){Z[b]=d},getTracker:function(b,
d){return new da(b,d)},getAsyncTracker:function(){return J}};"function"===typeof define&&define.amd&&define("piwik",[],function(){return W});return W}());window&&window.piwikAsyncInit&&window.piwikAsyncInit();(function(){"undefined"===typeof AnalyticsTracker&&(AnalyticsTracker=Piwik)})();
"function"!==typeof piwik_log&&(piwik_log=function(b,C,p,G){function d(b){try{return eval("piwik_"+b)}catch(d){}}var l=Piwik.getTracker(p,C);l.setDocumentTitle(b);l.setCustomData(G);(b=d("tracker_pause"))&&l.setLinkTrackingTimer(b);(b=d("download_extensions"))&&l.setDownloadExtensions(b);(b=d("hosts_alias"))&&l.setDomains(b);(b=d("ignore_classes"))&&l.setIgnoreClasses(b);l.trackPageView();d("install_tracker")&&(piwik_track=function(b,d,p,C){l.setSiteId(d);l.setTrackerUrl(p);l.trackLink(b,C)},l.enableLinkTracking())});
